graph TD
    A[Alimentos] -->|Executa Capacidade| B(Comercializar Produto Acabado)
    B --> C{App Força de Vendas}
    C -->|Bloco de Plataforma 1| D["Uniface TS Pool"]
    C -->|Bloco de Plataforma 2| E["File Server Cluster"]
    C -->|Bloco de Plataforma 3| F[fa:fa-orcl Oracle]
